{
  "x-generator": "NSwag v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "Payins",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://localhost:7292"
    }
  ],
  "paths": {
    "/refunds": {
      "post": {
        "tags": [
          "Refunds"
        ],
        "summary": "Create Refund",
        "description": "Use this endpoint to create a new refund.",
        "operationId": "BIOSPayinsEndpointsRefundsCreateRefundEndpoint",
        "requestBody": {
          "x-name": "CreateRefundRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSPayinsContractsRequestsCreateRefundRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "201": {
            "description": "The refund you have just created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesRefundContract"
                },
                "example": {
                  "id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "68a79198-25dd-4d29-b566-3d7d0c84c755",
                  "date": 1696426205617,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Refunds"
        ],
        "summary": "List Refunds",
        "description": "Use this endpoint to list all your refunds.",
        "operationId": "BIOSPayinsEndpointsRefundsListRefundsEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your refunds.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSPayinsContractsResponsesRefundContract"
                  }
                },
                "example": []
              }
            }
          }
        }
      }
    },
    "/refunds/{refund_id}": {
      "get": {
        "tags": [
          "Refunds"
        ],
        "summary": "Retrieve Refund",
        "description": "Use this endpoint to retrieve an existing refund.",
        "operationId": "BIOSPayinsEndpointsRefundsRetrieveRefundEndpoint",
        "parameters": [
          {
            "name": "refund_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The refund with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesRefundContract"
                },
                "example": {
                  "id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "4353a63e-6db4-4c0e-88a9-889ad8d8bad0",
                  "date": 1696426205623,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "88a2d39f-ef86-4f6b-8b0b-29b5d43d445e",
                  "date": 1696426205623,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Refunds"
        ],
        "summary": "Update Refund",
        "description": "Use this endpoint to update an existing refund.",
        "operationId": "BIOSPayinsEndpointsDisputesUpdateRefundEndpoint",
        "parameters": [
          {
            "name": "refund_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdateRefundRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSPayinsContractsRequestsUpdateRefundRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The refund you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesRefundContract"
                },
                "example": {
                  "id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "a39c7baf-756e-4359-b9b8-291803ee6033",
                  "date": 1696426205628,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "26032732-b293-40d3-b7c0-4c94eccb3dd7",
                  "date": 1696426205628,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/payins": {
      "post": {
        "tags": [
          "Payins"
        ],
        "summary": "Create Payin",
        "description": "Use this endpoint to create a new payin.",
        "operationId": "BIOSPayinsEndpointsPayinsCreatePayinEndpoint",
        "responses": {
          "401": {
            "description": "The request is not authorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "Access to the API resource is not authorized due to an authentication failure.",
                  "type": "unauthorized_access",
                  "id": "ff640c76-c1d1-40f7-ac88-84a3d6c2cc23",
                  "date": 1696426205625,
                  "errors": []
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "201": {
            "description": "The payin you have just created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsCreatePayinResponse"
                },
                "example": {
                  "id": "00000000-0000-0000-0000-000000000000"
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "794e36a5-a54c-4c02-83c7-3bbf713ef29b",
                  "date": 1696426205625,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Payins"
        ],
        "summary": "List Payins",
        "description": "Use this endpoint to list all your payins.",
        "operationId": "BIOSPayinsEndpointsPayinsListPayinsEndpoint",
        "responses": {
          "401": {
            "description": "The request is not authorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "Access to the API resource is not authorized due to an authentication failure.",
                  "type": "unauthorized_access",
                  "id": "c92d323b-a13a-4d0a-8702-af6130dfd00b",
                  "date": 1696426205626,
                  "errors": []
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your payins.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsListPayinsResponse"
                },
                "example": []
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "9c79c9d2-1f74-4cb5-a42a-eac711624256",
                  "date": 1696426205626,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/payins/{payin_id}": {
      "delete": {
        "tags": [
          "Payins"
        ],
        "summary": "Delete Payin",
        "description": "Use this endpoint to delete an existing Payin.",
        "operationId": "BIOSPayinsEndpointsPayinsDeletePayinEndpoint",
        "parameters": [
          {
            "name": "payin_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "The request is not authorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "Access to the API resource is not authorized due to an authentication failure.",
                  "type": "unauthorized_access",
                  "id": "05cad362-93a2-42ae-8673-0b45b7098b77",
                  "date": 1696426205626,
                  "errors": []
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "204": {
            "description": "The payin has been deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FastEndpointsEmptyResponse"
                },
                "example": {}
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "bc3f37ce-6cae-4c2a-b1a4-8d4cfbf35503",
                  "date": 1696426205626,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "c280d368-a844-4fe0-902c-91366b5c11f1",
                  "date": 1696426205626,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Payins"
        ],
        "summary": "Retrieve Payin",
        "description": "Use this endpoint to retrieve an existing payin.",
        "operationId": "BIOSPayinsEndpointsPayinsRetrievePayinEndpoint",
        "parameters": [
          {
            "name": "payin_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "The request is not authorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "Access to the API resource is not authorized due to an authentication failure.",
                  "type": "unauthorized_access",
                  "id": "cec1b756-3bbb-431b-a363-44510bd63068",
                  "date": 1696426205627,
                  "errors": []
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The payin with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsRetrievePayinResponse"
                },
                "example": {
                  "id": "00000000-0000-0000-0000-000000000000"
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "980053e4-9b4f-4d2b-b295-7d4ad08664fc",
                  "date": 1696426205627,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "7c323360-a1c7-4e20-8a21-9ab1ac9262f7",
                  "date": 1696426205627,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Payins"
        ],
        "summary": "Update Payin",
        "description": "Use this endpoint to update an existing payin.",
        "operationId": "BIOSPayinsEndpointsPayinsUpdatePayinEndpoint",
        "parameters": [
          {
            "name": "payin_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "The request is not authorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "Access to the API resource is not authorized due to an authentication failure.",
                  "type": "unauthorized_access",
                  "id": "2928fb75-8b5a-48b6-8533-95408a4679be",
                  "date": 1696426205628,
                  "errors": []
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The payin you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsUpdatePayinResponse"
                },
                "example": {
                  "id": "00000000-0000-0000-0000-000000000000"
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "bfdcae09-0463-4a81-afeb-a11071bc6888",
                  "date": 1696426205628,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "1752ed70-1905-4f95-ba84-883cb5f2565b",
                  "date": 1696426205628,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/disputes/{dispute_id}/accept": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "Accept Dispute",
        "description": "Use this endpoint to accept an open dispute.",
        "operationId": "BIOSPayinsEndpointsDisputesAcceptDisputeEndpoint",
        "parameters": [
          {
            "name": "dispute_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The dispute you have just accepted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesDisputeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "10152585-001a-4435-b95e-7757aee62681",
                  "date": 1696426205629,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "a766d976-9686-4c2b-9872-20fd519ebc98",
                  "date": 1696426205629,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/disputes/{dispute_id}/counter": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "Counter Dispute",
        "description": "Use this endpoint to update evidence for an open dispute.",
        "operationId": "BIOSPayinsEndpointsDisputesCounterDisputeEndpoint",
        "parameters": [
          {
            "name": "dispute_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "CounterDisputeRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSPayinsContractsRequestsCounterDisputeRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The dispute you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesDisputeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "3b661aa4-9792-4893-994c-0969641467e1",
                  "date": 1696426205629,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "f5f5fb74-3eb7-40d4-8182-12bac963117a",
                  "date": 1696426205629,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/disputes": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "List Disputes",
        "description": "Use this endpoint to list all your disputes.",
        "operationId": "BIOSPayinsEndpointsDisputesListDisputesEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your disputes.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSPayinsContractsResponsesDisputeContract"
                  }
                },
                "example": []
              }
            }
          }
        }
      }
    },
    "/disputes/{dispute_id}": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "Retrieve Dispute",
        "description": "Use this endpoint to retrieve an existing dispute.",
        "operationId": "BIOSPayinsEndpointsDisputesRetrieveDisputeEndpoint",
        "parameters": [
          {
            "name": "dispute_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The dispute with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesDisputeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "c361e8ec-055e-4cf5-a5ab-ed7e64309370",
                  "date": 1696426205630,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "b984fe27-961f-4859-b815-9c9662e23d12",
                  "date": 1696426205630,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "Update Dispute",
        "description": "Use this endpoint to update an existing dispute.",
        "operationId": "BIOSPayinsEndpointsDisputesUpdateDisputeEndpoint",
        "parameters": [
          {
            "name": "dispute_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdateDisputeRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSPayinsContractsRequestsUpdateDisputeRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The dispute you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesDisputeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "charge_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null,
                  "reason": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "cb9aaf7d-3ddc-48be-92ae-f2ee051d81a6",
                  "date": 1696426205631,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "ba967d4c-a578-45b6-b746-5f72e972270f",
                  "date": 1696426205631,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/charges": {
      "get": {
        "tags": [
          "Charges"
        ],
        "summary": "List Charges",
        "description": "Use this endpoint to list all your charges.",
        "operationId": "BIOSPayinsEndpointsChargesListChargesEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your charges.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSPayinsContractsResponsesChargeContract"
                  }
                },
                "example": []
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "eacc0b17-2985-4a0d-872f-a976ecc357a0",
                  "date": 1696426205632,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/charges/{charge_id}/refund": {
      "post": {
        "tags": [
          "Charges"
        ],
        "summary": "Refund Charge",
        "description": "Use this endpoint to refund an existing charge.",
        "operationId": "BIOSPayinsEndpointsChargesRefundChargeEndpoint",
        "parameters": [
          {
            "name": "charge_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The charge you have just Refunded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesChargeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "payin_id": null,
                  "payment_method_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "8faa9bba-a368-4c21-bced-22080feadd48",
                  "date": 1696426205632,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "6042c893-c2ba-4afa-a011-3dfeb5784b6f",
                  "date": 1696426205632,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/charges/{charge_id}": {
      "get": {
        "tags": [
          "Charges"
        ],
        "summary": "Retrieve Charge",
        "description": "Use this endpoint to retrieve an existing charge.",
        "operationId": "BIOSPayinsEndpointsChargesRetrieveChargeEndpoint",
        "parameters": [
          {
            "name": "charge_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The charge with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesChargeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "payin_id": null,
                  "payment_method_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "9bfa7303-7525-4ba6-9f5c-f5dc45db567f",
                  "date": 1696426205633,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "1ac6e225-8559-45a7-bf14-27d65405b8f5",
                  "date": 1696426205633,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Charges"
        ],
        "summary": "Update Charge",
        "description": "Use this endpoint to update an existing charge.",
        "operationId": "BIOSPayinsEndpointsChargesUpdateChargeEndpoint",
        "parameters": [
          {
            "name": "charge_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdateChargeRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSPayinsContractsRequestsUpdateChargeRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The charge you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSPayinsContractsResponsesChargeContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "payin_id": null,
                  "payment_method_id": null,
                  "amount": 0,
                  "currency": null,
                  "psp": null,
                  "psp_id": null,
                  "state": null
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "17a91f34-02e0-4597-a178-6d9ed1ac8b51",
                  "date": 1696426205634,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "692a779a-39ad-4e44-afc4-c24409efca1d",
                  "date": 1696426205634,
                  "errors": []
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BIOSPayinsContractsResponsesRefundContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "charge_id": {
            "type": "string"
          },
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "psp": {
            "type": "string"
          },
          "psp_id": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "BIOSCoreApiErrorResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "message": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "date": {
            "type": "integer",
            "format": "int64"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BIOSPayinsContractsRequestsCreateRefundRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "charge_id": {
            "type": "string",
            "nullable": true
          },
          "amount": {
            "type": "integer",
            "format": "int64",
            "nullable": true
          },
          "reason": {
            "type": "string",
            "nullable": true
          },
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "BIOSEventsMetadataOptions": {
        "type": "object",
        "additionalProperties": {
          "type": "string",
          "nullable": true
        }
      },
      "BIOSPayinsContractsCreatePayinResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSPayinsContractsPayinContract"
          },
          {
            "type": "object",
            "additionalProperties": false
          }
        ]
      },
      "BIOSPayinsContractsPayinContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string",
            "format": "guid"
          }
        }
      },
      "BIOSPayinsContractsCreatePayinRequest": {
        "type": "object",
        "additionalProperties": false
      },
      "FastEndpointsEmptyResponse": {
        "type": "object",
        "description": "a response dto that doesn't have any properties",
        "additionalProperties": false
      },
      "BIOSPayinsContractsListPayinsResponse": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/BIOSPayinsContractsPayinContract"
        }
      },
      "BIOSPayinsContractsRetrievePayinResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSPayinsContractsPayinContract"
          },
          {
            "type": "object",
            "additionalProperties": false
          }
        ]
      },
      "BIOSPayinsContractsUpdatePayinResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSPayinsContractsPayinContract"
          },
          {
            "type": "object",
            "additionalProperties": false
          }
        ]
      },
      "BIOSPayinsContractsUpdatePayinRequest": {
        "type": "object",
        "additionalProperties": false
      },
      "BIOSPayinsContractsRequestsUpdateRefundRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "BIOSPayinsContractsResponsesDisputeContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "seller_id": {
            "type": "string"
          },
          "charge_id": {
            "type": "string"
          },
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "psp": {
            "type": "string"
          },
          "psp_id": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "BIOSPayinsContractsRequestsCounterDisputeRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "access_activity_log": {
            "type": "string",
            "nullable": true
          },
          "billing_address": {
            "type": "string",
            "nullable": true
          },
          "cancellation_policy": {
            "type": "string",
            "nullable": true
          },
          "cancellation_policy_disclosure": {
            "type": "string",
            "nullable": true
          },
          "cancellation_rebuttal": {
            "type": "string",
            "nullable": true
          },
          "customer_communication": {
            "type": "string",
            "nullable": true
          },
          "customer_email_address": {
            "type": "string",
            "nullable": true
          },
          "customer_name": {
            "type": "string",
            "nullable": true
          },
          "customer_purchase_ip": {
            "type": "string",
            "nullable": true
          },
          "customer_signature": {
            "type": "string",
            "nullable": true
          },
          "duplicate_charge_documentation": {
            "type": "string",
            "nullable": true
          },
          "duplicate_charge_explanation": {
            "type": "string",
            "nullable": true
          },
          "duplicate_charge_id": {
            "type": "string",
            "nullable": true
          },
          "product_description": {
            "type": "string",
            "nullable": true
          },
          "receipt": {
            "type": "string",
            "nullable": true
          },
          "refund_policy": {
            "type": "string",
            "nullable": true
          },
          "refund_policy_disclosure": {
            "type": "string",
            "nullable": true
          },
          "refund_refusal_explanation": {
            "type": "string",
            "nullable": true
          },
          "service_date": {
            "type": "string",
            "nullable": true
          },
          "service_documentation": {
            "type": "string",
            "nullable": true
          },
          "shipping_address": {
            "type": "string",
            "nullable": true
          },
          "shipping_carrier": {
            "type": "string",
            "nullable": true
          },
          "shipping_date": {
            "type": "string",
            "nullable": true
          },
          "shipping_documentation": {
            "type": "string",
            "nullable": true
          },
          "shipping_tracking_number": {
            "type": "string",
            "nullable": true
          },
          "uncategorized_file": {
            "type": "string",
            "nullable": true
          },
          "uncategorized_text": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "BIOSPayinsContractsRequestsUpdateDisputeRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "BIOSPayinsContractsResponsesChargeContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "seller_id": {
            "type": "string"
          },
          "payin_id": {
            "type": "string"
          },
          "payment_method_id": {
            "type": "string"
          },
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "psp": {
            "type": "string"
          },
          "psp_id": {
            "type": "string"
          },
          "state": {
            "type": "string"
          }
        }
      },
      "BIOSPayinsContractsRequestsUpdateChargeRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      }
    }
  }
}