{
  "x-generator": "NSwag v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "Sellers",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://localhost:7183"
    }
  ],
  "paths": {
    "/sellers": {
      "post": {
        "tags": [
          "Sellers"
        ],
        "summary": "Create Seller",
        "description": "Use this endpoint to create a new seller profile.",
        "operationId": "BIOSSellersEndpointsSellersCreateSellerEndpoint",
        "requestBody": {
          "x-name": "CreateSellerRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsCreateSellerRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "201": {
            "description": "The seller you have just created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesSellerContract"
                },
                "example": {
                  "id": null,
                  "country": null,
                  "type": null,
                  "mcc": null,
                  "url": null,
                  "description": null,
                  "company": null,
                  "persons": null,
                  "bank_accounts": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "a91fac84-003a-4280-a0c6-a277658de3fc",
                  "date": 1696426205639,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Sellers"
        ],
        "summary": "List Sellers",
        "description": "Use this endpoint to list all your sellers.",
        "operationId": "BIOSSellersEndpointsSellersListSellersEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your sellers.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSSellersContractsResponsesSellerContract"
                  }
                },
                "example": []
              }
            }
          }
        }
      }
    },
    "/sellers/{seller_id}": {
      "delete": {
        "tags": [
          "Sellers"
        ],
        "summary": "Delete Seller",
        "description": "Use this endpoint to delete an existing seller profile.",
        "operationId": "BIOSSellersEndpointsSellersDeleteSellerEndpoint",
        "parameters": [
          {
            "name": "seller_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "204": {
            "description": "The seller has been deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FastEndpointsEmptyResponse"
                },
                "example": {}
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "6e31b10b-a8d9-4560-b1f8-fc39c3f551d9",
                  "date": 1696426205647,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "7f2c32bd-5495-493c-af9c-5f5e652e76fd",
                  "date": 1696426205647,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Sellers"
        ],
        "summary": "Retrieve Seller",
        "description": "Use this endpoint to retrieve an existing seller profile.",
        "operationId": "BIOSSellersEndpointsSellersRetrieveSellerEndpoint",
        "parameters": [
          {
            "name": "seller_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The seller with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesSellerContract"
                },
                "example": {
                  "id": null,
                  "country": null,
                  "type": null,
                  "mcc": null,
                  "url": null,
                  "description": null,
                  "company": null,
                  "persons": null,
                  "bank_accounts": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "8f928ba0-584b-4a9a-b3cb-df5eca1e6987",
                  "date": 1696426205649,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "66788457-9fde-484f-8ee9-67e3d1e5e467",
                  "date": 1696426205649,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Sellers"
        ],
        "summary": "Update Seller",
        "description": "Use this endpoint to update an existing seller profile.",
        "operationId": "BIOSSellersEndpointsSellersUpdateSellerEndpoint",
        "parameters": [
          {
            "name": "seller_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdateSellerRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsUpdateSellerRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The seller you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesSellerContract"
                },
                "example": {
                  "id": null,
                  "country": null,
                  "type": null,
                  "mcc": null,
                  "url": null,
                  "description": null,
                  "company": null,
                  "persons": null,
                  "bank_accounts": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "2c57deb4-6125-474b-9006-9a4385a6d71a",
                  "date": 1696426205649,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "669b5012-4867-4a24-8f82-b87a7e11b06e",
                  "date": 1696426205649,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/persons": {
      "post": {
        "tags": [
          "Persons"
        ],
        "summary": "Create Person",
        "description": "Use this endpoint to create a new person profile.",
        "operationId": "BIOSSellersEndpointsPersonsCreatePersonEndpoint",
        "requestBody": {
          "x-name": "CreatePersonRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsCreatePersonRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "201": {
            "description": "The person you have just created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesPersonContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "email": null,
                  "first_name": null,
                  "last_name": null,
                  "nationality": null,
                  "phone": null,
                  "date_of_birth": null,
                  "address": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "efa5da71-b60d-49c0-844c-4f14ef49864d",
                  "date": 1696426205652,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Persons"
        ],
        "summary": "List Persons",
        "description": "Use this endpoint to list all your persons.",
        "operationId": "BIOSSellersEndpointsPersonsListPersonsEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your persons.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSSellersContractsResponsesPersonContract"
                  }
                },
                "example": []
              }
            }
          }
        }
      }
    },
    "/persons/{person_id}": {
      "delete": {
        "tags": [
          "Persons"
        ],
        "summary": "Delete person",
        "description": "Use this endpoint to delete an existing person profile.",
        "operationId": "BIOSSellersEndpointsPersonsDeletePersonEndpoint",
        "parameters": [
          {
            "name": "person_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "204": {
            "description": "The person has been deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FastEndpointsEmptyResponse"
                },
                "example": {}
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "2dd1badd-f360-4f3b-8677-01b8b657cadd",
                  "date": 1696426205655,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "754f2dbe-9d1f-4d5c-89e0-ec75b0dc3974",
                  "date": 1696426205655,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Persons"
        ],
        "summary": "Retrieve Person",
        "description": "Use this endpoint to retrieve an existing person profile.",
        "operationId": "BIOSSellersEndpointsPersonsRetrievePersonEndpoint",
        "parameters": [
          {
            "name": "person_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The person with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesPersonContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "email": null,
                  "first_name": null,
                  "last_name": null,
                  "nationality": null,
                  "phone": null,
                  "date_of_birth": null,
                  "address": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "6670af43-be9f-45b8-be86-36a964366b0e",
                  "date": 1696426205657,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "acdea886-08b9-44f1-ab25-5f9e8b395ead",
                  "date": 1696426205657,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Persons"
        ],
        "summary": "Update Person",
        "description": "Use this endpoint to update an existing person profile.",
        "operationId": "BIOSSellersEndpointsPersonsUpdatePersonEndpoint",
        "parameters": [
          {
            "name": "person_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdatePersonRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsUpdatePersonRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The person you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesPersonContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "email": null,
                  "first_name": null,
                  "last_name": null,
                  "nationality": null,
                  "phone": null,
                  "date_of_birth": null,
                  "address": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "583b1345-b7c9-4a40-a4ab-d6eec88616a9",
                  "date": 1696426205659,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "ec64e676-19d4-49bd-8237-b9641bbda9cc",
                  "date": 1696426205659,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/companies": {
      "post": {
        "tags": [
          "Companies"
        ],
        "summary": "Create Company",
        "description": "Use this endpoint to create a new company profile.",
        "operationId": "BIOSSellersEndpointsCompaniesCreateCompanyEndpoint",
        "requestBody": {
          "x-name": "CreateCompanyRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsCreateCompanyRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "201": {
            "description": "The company you have just created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesCompanyContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "name": null,
                  "phone": null,
                  "registration_number": null,
                  "structure": null,
                  "address": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "af94294b-9def-4e68-8127-5ce9adc05caf",
                  "date": 1696426205659,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "List Companies",
        "description": "Use this endpoint to list all your companies.",
        "operationId": "BIOSSellersEndpointsCompaniesListCompaniesEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your companies.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSSellersContractsResponsesCompanyContract"
                  }
                },
                "example": []
              }
            }
          }
        }
      }
    },
    "/companies/{company_id}": {
      "delete": {
        "tags": [
          "Companies"
        ],
        "summary": "Delete Company",
        "description": "Use this endpoint to delete an existing company profile.",
        "operationId": "BIOSSellersEndpointsCompaniesDeleteCompanyEndpoint",
        "parameters": [
          {
            "name": "company_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "204": {
            "description": "The company has been deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FastEndpointsEmptyResponse"
                },
                "example": {}
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "23d33fc4-1a07-44fd-b9b4-68f56bab10e4",
                  "date": 1696426205660,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "d84bb9c6-5352-46d1-a1a8-973cf1977f67",
                  "date": 1696426205660,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "Retrieve Company",
        "description": "Use this endpoint to retrieve an existing company profile.",
        "operationId": "BIOSSellersEndpointsCompaniesRetrieveCompanyEndpoint",
        "parameters": [
          {
            "name": "company_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The company with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesCompanyContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "name": null,
                  "phone": null,
                  "registration_number": null,
                  "structure": null,
                  "address": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "2bc7160f-0c53-4673-8295-0fd142529b7c",
                  "date": 1696426205661,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "93014eb1-7e54-423b-a139-09fe231a1485",
                  "date": 1696426205661,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Companies"
        ],
        "summary": "Update Company",
        "description": "Use this endpoint to update an existing company profile.",
        "operationId": "BIOSSellersEndpointsCompaniesUpdateCompanyEndpoint",
        "parameters": [
          {
            "name": "company_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdateCompanyRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsUpdateCompanyRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The company you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesCompanyContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "name": null,
                  "phone": null,
                  "registration_number": null,
                  "structure": null,
                  "address": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "3881f9db-1341-424e-b22a-02ebf060b488",
                  "date": 1696426205661,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "f2ca0458-0cb6-44b7-a564-0e9d14b91460",
                  "date": 1696426205661,
                  "errors": []
                }
              }
            }
          }
        }
      }
    },
    "/bankaccounts": {
      "post": {
        "tags": [
          "Bankaccounts"
        ],
        "summary": "Create Bank Account",
        "description": "Use this endpoint to create a new bank account profile.",
        "operationId": "BIOSSellersEndpointsBankAccountsCreateBankAccountEndpoint",
        "requestBody": {
          "x-name": "CreateBankAccountRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsCreateBankAccountRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "201": {
            "description": "The bank account you have just created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesBankAccountContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "country": null,
                  "currency": null,
                  "account_number": null,
                  "holder_name": null,
                  "holder_type": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "15e99faa-5d3d-4a12-81ca-30eb250b3cfa",
                  "date": 1696426205662,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Bankaccounts"
        ],
        "summary": "List Bank Accounts",
        "description": "Use this endpoint to list all your bank accounts.",
        "operationId": "BIOSSellersEndpointsBankAccountsListBankAccountsEndpoint",
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "A list of your bank Accounts.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BIOSSellersContractsResponsesBankAccountContract"
                  }
                },
                "example": []
              }
            }
          }
        }
      }
    },
    "/bankaccounts/{bank_account_id}": {
      "delete": {
        "tags": [
          "Bankaccounts"
        ],
        "summary": "Delete Bank Account",
        "description": "Use this endpoint to delete an existing bank account profile.",
        "operationId": "BIOSSellersEndpointsBankAccountsDeleteBankAccountEndpoint",
        "parameters": [
          {
            "name": "bank_account_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "204": {
            "description": "The bank account has been deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FastEndpointsEmptyResponse"
                },
                "example": {}
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "8c0f28d2-d22b-4d5d-80ca-bfa1f9f030b4",
                  "date": 1696426205663,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "7ba715cc-1bb3-470a-9910-5ffaafb8318d",
                  "date": 1696426205663,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Bankaccounts"
        ],
        "summary": "Retrieve Bank Account",
        "description": "Use this endpoint to retrieve an existing bank account profile.",
        "operationId": "BIOSSellersEndpointsBankAccountsRetrieveBankAccountEndpoint",
        "parameters": [
          {
            "name": "bank_account_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The bank account with the ID you provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesBankAccountContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "country": null,
                  "currency": null,
                  "account_number": null,
                  "holder_name": null,
                  "holder_type": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "619d6809-b59b-45c5-8682-da936edb2215",
                  "date": 1696426205664,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "34b6af16-dbf8-4d55-bbda-1d0535e76ebf",
                  "date": 1696426205664,
                  "errors": []
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Bankaccounts"
        ],
        "summary": "Update Bank Account",
        "description": "Use this endpoint to update an existing bank account profile.",
        "operationId": "BIOSSellersEndpointsBankAccountsUpdateBankAccountEndpoint",
        "parameters": [
          {
            "name": "bank_account_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "x-name": "UpdateBankAccountRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsUpdateBankAccountRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "200": {
            "description": "The bank account you have just updated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSSellersContractsResponsesBankAccountContract"
                },
                "example": {
                  "id": null,
                  "seller_id": null,
                  "country": null,
                  "currency": null,
                  "account_number": null,
                  "holder_name": null,
                  "holder_type": null,
                  "metadata": {}
                }
              }
            }
          },
          "400": {
            "description": "The request did not pass validation checks.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "One or more error occurred",
                  "type": "bad_request",
                  "id": "1eeddfd3-2ae2-4de6-85d8-81baf7efc263",
                  "date": 1696426205665,
                  "errors": []
                }
              }
            }
          },
          "404": {
            "description": "Resource not found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BIOSCoreApiErrorResponse"
                },
                "example": {
                  "message": "The requested resource cannot be found.",
                  "type": "not_found",
                  "id": "6fe3ce75-803d-4e14-be84-c91832fb3442",
                  "date": 1696426205665,
                  "errors": []
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BIOSSellersContractsResponsesSellerContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "mcc": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "url": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "company": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsResponsesCompanyContract"
              }
            ]
          },
          "persons": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BIOSSellersContractsResponsesPersonContract"
            }
          },
          "bank_accounts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BIOSSellersContractsResponsesBankAccountContract"
            }
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "BIOSSellersContractsResponsesCompanyContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "seller_id": {
            "type": "string"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "registration_number": {
            "type": "string",
            "nullable": true
          },
          "structure": {
            "type": "string",
            "nullable": true
          },
          "address": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsResponsesAddressContract"
              }
            ]
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "BIOSSellersContractsResponsesAddressContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "city": {
            "type": "string"
          },
          "line1": {
            "type": "string"
          },
          "line2": {
            "type": "string",
            "nullable": true
          },
          "state": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "postal_code": {
            "type": "string"
          }
        }
      },
      "BIOSSellersContractsResponsesPersonContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "seller_id": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "first_name": {
            "type": "string",
            "nullable": true
          },
          "last_name": {
            "type": "string",
            "nullable": true
          },
          "nationality": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "date_of_birth": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsResponsesDateOfBirthContract"
              }
            ]
          },
          "address": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsResponsesAddressContract"
              }
            ]
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "BIOSSellersContractsResponsesDateOfBirthContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "day": {
            "type": "integer",
            "format": "int32"
          },
          "month": {
            "type": "integer",
            "format": "int32"
          },
          "year": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "BIOSSellersContractsResponsesBankAccountContract": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "seller_id": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "currency": {
            "type": "string"
          },
          "account_number": {
            "type": "string"
          },
          "holder_name": {
            "type": "string",
            "nullable": true
          },
          "holder_type": {
            "type": "string",
            "nullable": true
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "BIOSCoreApiErrorResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "message": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "date": {
            "type": "integer",
            "format": "int64"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BIOSSellersContractsRequestsCreateSellerRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsSellerOptions"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "type": {
                "type": "string",
                "nullable": true
              },
              "country": {
                "type": "string",
                "nullable": true
              }
            }
          }
        ]
      },
      "BIOSSellersContractsRequestsSellerOptions": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "mcc": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "url": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "company": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsCompanyOptions"
              }
            ]
          },
          "persons": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BIOSSellersContractsRequestsPersonOptions"
            }
          },
          "bank_accounts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BIOSSellersContractsRequestsBankAccountOptions"
            }
          },
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "BIOSSellersContractsRequestsCompanyOptions": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "registration_number": {
            "type": "string",
            "nullable": true
          },
          "structure": {
            "type": "string",
            "nullable": true
          },
          "address": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsAddressOptions"
              }
            ]
          },
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "BIOSSellersContractsRequestsAddressOptions": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "city": {
            "type": "string"
          },
          "line1": {
            "type": "string"
          },
          "line2": {
            "type": "string",
            "nullable": true
          },
          "state": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "postal_code": {
            "type": "string"
          }
        }
      },
      "BIOSEventsMetadataOptions": {
        "type": "object",
        "additionalProperties": {
          "type": "string",
          "nullable": true
        }
      },
      "BIOSSellersContractsRequestsPersonOptions": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "email": {
            "type": "string",
            "nullable": true
          },
          "first_name": {
            "type": "string",
            "nullable": true
          },
          "last_name": {
            "type": "string",
            "nullable": true
          },
          "nationality": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "dob": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsDateOfBirthOptions"
              }
            ]
          },
          "address": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSSellersContractsRequestsAddressOptions"
              }
            ]
          },
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "BIOSSellersContractsRequestsDateOfBirthOptions": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "day": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "month": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "year": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          }
        }
      },
      "BIOSSellersContractsRequestsBankAccountOptions": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "country": {
            "type": "string",
            "nullable": true
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "account_number": {
            "type": "string",
            "nullable": true
          },
          "holder_name": {
            "type": "string",
            "nullable": true
          },
          "holder_type": {
            "type": "string",
            "nullable": true
          },
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      },
      "FastEndpointsEmptyResponse": {
        "type": "object",
        "description": "a response dto that doesn't have any properties",
        "additionalProperties": false
      },
      "BIOSSellersContractsRequestsUpdateSellerRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsSellerOptions"
          },
          {
            "type": "object",
            "additionalProperties": false
          }
        ]
      },
      "BIOSSellersContractsRequestsCreatePersonRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsPersonOptions"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "seller_id": {
                "type": "string",
                "nullable": true
              }
            }
          }
        ]
      },
      "BIOSSellersContractsRequestsUpdatePersonRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsPersonOptions"
          },
          {
            "type": "object",
            "additionalProperties": false
          }
        ]
      },
      "BIOSSellersContractsRequestsCreateCompanyRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsCompanyOptions"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "seller_id": {
                "type": "string",
                "nullable": true
              }
            }
          }
        ]
      },
      "BIOSSellersContractsRequestsUpdateCompanyRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsCompanyOptions"
          },
          {
            "type": "object",
            "additionalProperties": false
          }
        ]
      },
      "BIOSSellersContractsRequestsCreateBankAccountRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/BIOSSellersContractsRequestsBankAccountOptions"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "seller_id": {
                "type": "string",
                "nullable": true
              }
            }
          }
        ]
      },
      "BIOSSellersContractsRequestsUpdateBankAccountRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "holder_name": {
            "type": "string",
            "nullable": true
          },
          "holder_type": {
            "type": "string",
            "nullable": true
          },
          "metadata": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/BIOSEventsMetadataOptions"
              }
            ]
          }
        }
      }
    }
  }
}